# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: true

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#addons
addons:
  apt:
    packages:
    - libmagick++-dev
    - libssh2-1-dev

#matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
    env:
      - DEPLOY_PAGES=true
    before_script:
      - scripts/deploy-pages.sh install
  - r: oldrel
  - r: devel
  - os: osx
    osx_image: xcode7.2
    r: release
    latex: false

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

#deploy (to gh-pages)
deploy:
  provider: script
  script: scripts/deploy-pages.sh
  on:
    branch: production

#after_success (run covr)
after_success:
- R -e 'covr::codecov()'

# Custom parts:

#r_github_packages
r_github_packages:
- jimhester/covr

#r_packages
r_packages:

#services
services:

#before_install
before_install:

#before_script
before_script:
