# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: true

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - R_TRAVIS_TASKS="covr::codecov();"

#addons
addons:
  apt:
    packages:
    - libmagick++-dev
    - libssh2-1-dev

#matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
    env:
    - RTRAVIS_TASKS="${R_TRAVIS_TASKS} pkgdown::build_site(); task_install_ssh_keys()"
  - r: oldrel
  - r: devel
  - os: osx
    osx_image: xcode7.2
    r: release
    latex: false

#before_script
before_script:
- R -e 'travis::install_deploy_dependencies()'

#deploy (to gh-pages)
deploy:
- provider: script
  script: travis::deploy()

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

# Custom parts:

#r_github_packages
r_github_packages:
- ropenscilabs/travis@f-42-config

#r_packages
r_packages:

#services
services:

#before_install
before_install:

#before_script
before_script:
